apiVersion: apps/v1
kind: Deployment
metadata:
  name:frd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frd
  template:
    metadata:
      labels:
        app: frd
    spec:
      containers:
      - image: okteto.dev/frd:latest
        name: frd
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "icook.tw"
        - name: Vless_UUID
          value: "07f0668d-00d5-439c-b2a3-4998bc8525bf"
        - name: Vless_Path
          value: "/fwvfgARFYg"
        - name: Vmess_UUID
          value: "07f0668d-00d5-439c-b2a3-4998bc8525bf"
        - name: Vmess_Path
          value: "/CFVGYcfngty"
        - name: Share_Path
          value: "/share233"
